; hardware_in_loop/platformio.ini
[env:hardware_in_loop]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_flags = 
  -I ../include
  -D ARDUINO_USB_MODE=1
  -D ARDUINO_USB_CDC_ON_BOOT=1
monitor_speed = 115200
