; hardware_in_loop/platformio.ini

[env:hardware_in_loop]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.cdc_on_boot = 1
build_flags =
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=1
build_src_filter =
	-<*>
	+<hardware_in_loop/src/>
monitor_speed = 115200
