; PlatformIO Project Configuration File
;
; Each environment is fully defined in its own sub-config file.
; Do not duplicate environment settings here.
;
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = .
extra_configs =
	mainboard/platformio.ini
	hardware_in_loop/platformio.ini
