[env:display]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.arduino.cdc_on_boot = 1
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++17
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_SPEED_120M=1
    -DCONFIG_SPIRAM_FETCH_INSTRUCTIONS=1
    -DCONFIG_SPIRAM_RODATA=1
    -DCONFIG_SPIRAM_USE_MALLOC=1
    -O2
    -DCONFIG_FREERTOS_HZ=1000
    -DCONFIG_ESP32S3_DATA_CACHE_LINE_64B=1
    -DLV_CONF_INCLUDE_SIMPLE
    -Idisplay/lib
    -Idisplay/src
build_src_filter =
    -<*>
    +<display/src/>
lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git
    https://github.com/esp-arduino-libs/esp-lib-utils.git
lib_extra_dirs =
    display/lib
monitor_speed = 115200
monitor_filters =
    default
    time
upload_speed = 921600
